version: '3.8'
services:
  depr:
    image: ghcr.io/jacexh/derp-docker:v1.54.0
    container_name: derper
    restart: unless-stopped
    environment:
    - DERPER_DOMAIN=hub.foobar.com
    ports:
    - "443:443"
    - "3478:3478"
